markdown: redcarpet2
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
baseurl: /zobten-workflow
exclude: ['README.md', 'robots.txt']
permalink: pretty
